import React, { useState, useEffect, useRef } from 'react';
import { View, StyleSheet, TouchableOpacity, Text, Alert, Dimensions, Image } from 'react-native';
import * as MediaLibrary from 'expo-media-library';
import { captureRef } from 'react-native-view-shot';
import Header from './Header';
import { useNavigation } from '@react-navigation/native';
import { supabase } from '../../lib/supabase'; 
import AsyncStorage from '@react-native-async-storage/async-storage';


const { width: screenWidth } = Dimensions.get('window'); // Get screen width

const PaintByNumbers = () => {
  const navigation = useNavigation();
  const [userID, setUserId] = useState(null);
  const NUM_ROWS = 10; // Constant for the number of rows
  const columns = 10; // Number of columns in the grid
  const gridSize = NUM_ROWS * columns; // Total number of cells in the grid
  
  const [headerText, setHeaderText] = useState('0'); 
  const [selectedColor, setSelectedColor] = useState(null);
  const [grid, setGrid] = useState(Array(gridSize).fill(null)); // 10x10 grid
  const [colors, setColors] = useState([]);
  const [currentPrompt, setCurrentPrompt] = useState('');
  const [galleryImages, setGalleryImages] = useState([]); // New state to store gallery images
  const paintRef = useRef();

  const handleHomePress = () => {
    console.log("Home button pressed");
    navigation.navigate('Home'); 
  };

  const gridMargin = 20; // Margin around the grid
  const maxGridWidth = screenWidth * 0.8; // Maximum width for the grid (80% of screen width)

  const getRandomColor = () => {
    const randomColor = `#${Math.floor(Math.random() * 16777215).toString(16)}`;
    return randomColor;
  };

  const generateRandomColors = () => {
    const newColors = new Set();
    while (newColors.size < 5) {
      newColors.add(getRandomColor());
    }
    setColors(Array.from(newColors)); // Convert Set back to Array
  };

  const replaceRandomColor = () => {
    const newColor = getRandomColor();
    const randomIndex = Math.floor(Math.random() * colors.length);
    setColors((prevColors) => {
      const updatedColors = [...prevColors];
      updatedColors[randomIndex] = newColor;
      return updatedColors;
    });
  };

  useEffect(() => {
    generateRandomColors();
  }, []);

  const handleCellPress = (index) => {
    if (selectedColor) {
      const newGrid = [...grid];
      newGrid[index] = selectedColor;
      setGrid(newGrid);
    }
  };

  const pickRandomPrompt = () => {
    const prompts = [
      "A bright sun smiling in the sky",
     "Colorful flowers blooming in a field",
     "A serene beach with gentle waves",
     "A cozy cabin in the woods",
     "A rainbow after a light rain",
     "A whimsical treehouse",
     "A garden full of butterflies",
     "A peaceful lake with ducks",
     "A mountain landscape at sunrise",
     "A vibrant sunset over the ocean",
     "A field of sunflowers facing the sun",
     "A cozy campfire surrounded by trees",
     "A snowy landscape with a snowman",
     "A cherry blossom tree in full bloom",
     "A playful puppy in a grassy field",
     "A kite flying high in the sky",
     "A gentle waterfall in a forest",
     "A whimsical mushroom village",
     "A hot air balloon festival",
     "A cozy picnic setup in the park",
     "A smiling cat playing with yarn",
     "A happy dog wagging its tail",
     "A cute bunny hopping through the grass",
     "A cheerful penguin sliding on ice",
     "A colorful parrot sitting on a branch",
     "A friendly dolphin jumping in the ocean",
     "A playful kitten chasing a butterfly",
     "A cartoonish elephant spraying water",
     "A flock of cheerful birds in the sky",
     "A cuddly teddy bear with a big smile",
     "A happy squirrel gathering acorns",
     "A lazy sloth hanging from a tree",
     "A baby deer peeking through bushes",
     "A family of turtles sunbathing on a rock",
     "A dancing fox in a forest clearing",
     "A cheerful ladybug on a leaf",
     "A playful seal balancing a ball",
     "A group of friendly fish swimming together",
     "A colorful snail with a shiny shell",
     "A happy hedgehog with flowers",
     "A joyful raccoon exploring a garden",
     "A whimsical owl wearing glasses",
     "A cartoon whale splashing in the sea",
     "A fluffy alpaca with a colorful scarf",
     "A friendly crab waving on the beach",
     "A bright rainbow fish swimming in a pond",
     "A singing frog on a lily pad",
     "A pair of lovebirds in a tree",
     "A tiny mouse holding a piece of cheese",
     "A happy goat on a grassy hill",
     "A whimsical unicorn in a magical forest",
     "A cute fox peeking out from behind a tree",
     "A playful puppy in a field of flowers",
     "A cheerful baby elephant spraying water",
     "A colorful butterfly resting on a flower",
     "A whimsical dragon flying in the sky",
     "A happy kangaroo with a baby in its pouch",
     "A joyful otter floating on its back",
     "A family of ducks waddling by a pond",
     "A smiling sun with sunglasses",
     "A friendly monster with big eyes",
     "A cartoon bear holding a honey pot",
     "A cheerful chipmunk with acorns",
     "A colorful iguana on a branch",
     "A dancing parrot on a tropical island",
     "A group of children playing in a park",
     "A whimsical tree with smiling faces",
     "A magical fairy sitting on a mushroom",
     "A cheerful snowman with a carrot nose",
     "A bright yellow taxi in a busy city",
     "A cozy coffee shop with happy customers",
     "A peaceful village with colorful houses",
     "A happy family having a barbecue",
     "A rainbow-colored bicycle by a park",
     "A serene hammock between two palm trees",
     "A joyful girl flying a kite",
     "A colorful carousel with happy children",
     "A sunny day at the amusement park",
     "A friendly giant with a big smile",
     "A cheerful flower shop bursting with colors",
     "A colorful market with fresh fruits",
     "A bright red barn on a sunny day",
     "A happy ice cream truck parked in a park",
     "A smiling chef with a giant cupcake",
     "A cheerful panda eating bamboo",
     "A playful otter in a sparkling river",
     "A sunny garden with blooming daisies",
     "A whimsical hot air balloon floating in the sky",
     "A playful raccoon digging through a trash can",
     "A happy bear hugging a tree",
     "A colorful kite festival in the park",
     "A bright and sunny day at the beach",
     "A playful dolphin jumping through waves",
     "A friendly cat lounging in a sunny window",
     "A cheerful snowflake dancing in the air",
     "A cozy blanket fort with fairy lights",
     "A happy snail leaving a colorful trail",
     "A sunny day in a flower garden",
     "A whimsical castle in the clouds",
     "A friendly robot waving hello",
     "A joyful puppy playing in the rain",
     "A bright and colorful paint palette",
     "A group of children building a sandcastle",
     "A cheerful birdhouse in a tree",
     "A happy family on a picnic",
     "A whimsical village with quirky houses",
     "A colorful jigsaw puzzle in progress",
     "A smiling planet with rings",
     "A cozy reading nook with plush pillows",
     "A playful kitten in a box",
     "A bright sunflower turning towards the sun",
     "A magical garden with glowing plants",
     "A happy bear fishing in a stream",
     "A joyful celebration with balloons and confetti",
     "A bright orange sunset over the mountains",
     "A cheerful gingerbread house",
     "A whimsical circus with happy performers",
     "A colorful rainbow stretching across the sky",
     "A playful puppy chasing a butterfly",
     "A smiling cupcake with sprinkles",
     "A group of friends dancing at a party",
     "A happy cat lounging on a windowsill",
     "A vibrant fruit bowl overflowing with colors",
     "A bright beach umbrella on a sunny day",
     "A whimsical snow globe with a winter scene",
     "A cozy fireplace with happy family moments",
     "A cheerful pumpkin in a patch",
     "A bright flower crown on a girl's head",
     "A happy little gnome in a garden",
     "A joyful raccoon at a campsite",
     "A colorful peacock displaying its feathers",
     "A serene park with children playing",
     "A smiling frog playing a guitar",
     "A happy chef in a busy kitchen",
     "A whimsical windmill in a sunny field",
     "A cheerful owl perched on a tree branch",
     "A colorful train traveling through the countryside",
     "A playful monkey swinging from vines",
     "A happy baby riding a bicycle",
     "A cozy blanket and a cup of tea",
     "A bright rainbow stretching over a field",
     "A happy family portrait in a park",
     "A joyful girl dancing in a flower field",
     "A colorful fruit stand at a market",
     "A smiling whale swimming in the ocean",
     "A playful sea turtle swimming among coral",
     "A cheerful farmer in a field of crops",
     "A bright and colorful flower bouquet",
     "A joyful family playing games together",
     "A sunny day at a fair with rides",
     "A cheerful sun peeking through the clouds",
     "A playful dolphin painting in the sea",
     "A bright ice cream cone on a hot day",
     "A cozy blanket and a good book",
     "A whimsical fairy flying among flowers",
     "A cheerful sun and moon in the sky",
     "A happy dog playing fetch",
     "A colorful sunset over a city skyline",
     "A joyful girl spinning in a flower field",
     "A whimsical castle with colorful flags",
     "A playful puppy in a pile of leaves",
     "A bright and happy playground",
     "A cheerful ginger cat sleeping on a porch",
     "A sunny park with children playing tag",
     "A cozy tea party with stuffed animals",
     "A bright butterfly landing on a flower",
     "A happy snowman wearing a scarf",
     "A joyful dance party with friends",
     "A colorful peacock in a sunny garden",
     "A playful panda climbing a tree",
     "A cheerful elephant spraying water",
     "A bright starry night sky",
     "A happy garden with bees buzzing",
     "A cozy cabin with smoke coming from the chimney",
     "A playful puppy digging in the sand",
     "A whimsical fairy tale book with illustrations",
     "A joyful child jumping in puddles",
     "A colorful sailboat on a sunny day",
     "A cheerful penguin sliding on snow",
     "A bright yellow sun with happy rays",
     "A happy group of kids playing soccer",
     "A whimsical lighthouse by the sea",
     "A joyful puppy wagging its tail",
     "A colorful dragonfly buzzing around",
     "A happy baby playing with blocks",
     "A cheerful flower garden in spring",
     "A bright and sunny farmer's market",
     "A joyful child playing in a fountain",
     "A cozy home with a welcome mat",
     "A playful dolphin jumping through a hoop",
     "A cheerful hedgehog exploring a garden",
     "A bright and sunny hillside",
     "A happy cat chasing its tail",
     "A whimsical mushroom house",
     "A joyful picnic in a meadow",
     "A colorful birdhouse with birds",
     "A cheerful fox in a flower field",
     "A happy kid riding a scooter",
     "A bright rainbow arching over hills",
     "A playful seal balancing a ball on its nose",
     "A whimsical jellyfish floating in the sea",
     "A joyful family playing catch in the park",
     "A sunny day with children riding bikes",
     "A colorful paper airplane flying through the sky",
     "A cheerful whale breaching the ocean surface",
     "A happy squirrel munching on a nut",
     "A cozy reading corner with soft pillows",
     "A bright blue sky with fluffy clouds",
     "A joyful child blowing bubbles",
     "A whimsical fairy dancing in the moonlight",
     "A happy sunflower with a smiley face",
     "A playful otter sliding down a hill",
     "A bright and colorful fireworks display",
     "A cheerful girl dancing in the rain",
     "A happy family at a birthday party",
     "A colorful picnic blanket with food",
     "A joyful parrot singing on a branch",
     "A bright kite flying in a clear sky",
     "A playful kitten in a ball of yarn",
     "A cheerful sun shining over a park",
     "A whimsical carousel with happy animals",
     "A happy dog sticking its head out of a car window",
     "A colorful birthday cake with candles",
     "A joyful child making a sandcastle",
     "A cozy home with a garden",
     "A bright hot air balloon in the sky",
     "A playful rabbit hopping in a meadow",
     "A cheerful family enjoying a movie night",
     "A happy child feeding ducks at a pond",
     "A whimsical fairy house in the woods",
     "A bright flower pot on a windowsill",
     "A joyful girl twirling in a dress",
     "A cheerful garden gnome in a flower bed",
     "A happy snowman with a carrot nose and scarf",
     "A colorful candy shop filled with treats",
     "A playful puppy chasing after a ball",
     "A bright and sunny day at the zoo",
     "A joyful child playing in a leaf pile",
     "A whimsical pirate ship sailing the seas",
     "A happy family hiking on a sunny day",
     "A colorful village with balloons in the sky",
     "A cheerful frog leaping on lily pads",
     "A bright flower crown on a girl's head",
     "A joyful beach day with surfboards",
     "A cozy winter cabin with lights",
     "A playful kitten playing with a feather",
     "A cheerful tree with colorful leaves",
     "A bright and sunny day with butterflies",
     "A happy couple enjoying a sunset",
     "A whimsical fish swimming in a bubble",
     "A joyful dog jumping through hoops",
     "A colorful candy cane forest",
     "A bright and cheerful ice cream parlor",
     "A happy dog enjoying a sunny day",
     "A whimsical fox peeking out from behind a bush",
     "A colorful painting palette with brushes",
     "A cheerful rainbow with a pot of gold",
     "A happy family making a snowman",
     "A bright garden with vegetables growing",
     "A joyful girl flying a colorful kite",
     "A whimsical snail with a patterned shell",
     "A cheerful elephant spraying water",
     "A playful raccoon climbing a tree",
     "A colorful butterfly fluttering by",
     "A bright and happy farm scene",
     "A joyful picnic under a shady tree",
     "A cozy living room with happy moments",
     "A cheerful hot air balloon festival",
     "A happy child playing hopscotch",
     "A whimsical dragon flying through clouds",
     "A colorful paper crane flying in the wind",
     "A joyful puppy playing with a friend",
     "A bright sun shining over a field",
     "A happy child drawing with chalk",
     "A cheerful baby duckling waddling",
     "A cozy kitchen filled with baked goods",
     "A whimsical treehouse in a sunny park",
     "A joyful family decorating a Christmas tree",
     "A bright garden filled with bees",
     "A playful dolphin splashing in the ocean",
     "A cheerful scarecrow in a field",
     "A colorful playground filled with kids",
     "A happy monkey swinging from a tree",
     "A whimsical fairy flying among flowers",
     "A joyful puppy exploring a garden",
     "A bright rainbow with smiling clouds",
     "A happy child dancing in the rain",
     "A cheerful giraffe reaching for leaves",
     "A playful kitten playing with a butterfly",
     "A bright and sunny picnic scene",
     "A whimsical elephant playing in a puddle",
     "A joyful day at the beach with friends",
     "A cozy corner with plants and sunlight",
     "A cheerful flower arrangement in a vase",
     "A bright blue bird sitting on a branch",
     "A playful bear catching fish in a river",
     "A colorful jigsaw puzzle of a happy scene",
     "A joyful child running through a field",
     "A whimsical castle in a sunny landscape",
     "A bright star shining in the night sky",
     "A happy child painting a picture",
     "A cheerful ladybug on a leaf",
     "A colorful fish swimming in clear water",
     "A playful otter floating in a river",
     "A joyful family playing board games",
     "A bright balloon floating in the sky",
     "A happy cat chasing a string",
     "A whimsical tree with hanging lanterns",
     "A cheerful snowflake falling from the sky",
     "A playful seal balancing a fish",
     "A colorful flower field under a blue sky",
     "A joyful girl spinning with her arms open",
     "A bright and happy butterfly garden",
     "A happy dog running through tall grass",
     "A whimsical birdhouse with birds singing",
     "A cheerful painting of a sunny day",
     "A cozy coffee shop filled with laughter",
     "A playful rabbit in a vegetable garden",
     "A bright sun illuminating a forest",
     "A joyful family dancing together",
     "A colorful festival with lights and decorations",
     "A happy girl wearing a flower crown",
     "A cheerful elephant splashing water in a river",
     "A whimsical night sky filled with stars",
     "A playful kitten hiding in a box",
     "A bright rainbow arching over the hills",
     "A joyful child exploring a flower garden",
     "A cozy home with a warm fireplace",
     "A happy family enjoying a day at the zoo",
     "A cheerful snowman with a scarf and hat",
     "A colorful beach scene with umbrellas",
     "A playful dolphin jumping through waves",
     "A joyful family decorating a gingerbread house",
     "A whimsical fairy flying over a pond",
     "A bright and sunny garden with butterflies",
     "A happy dog catching a frisbee",
     "A cheerful child playing with a puppy",
     "A whimsical castle with a rainbow bridge",
     "A joyful family having a barbecue in the backyard",
     "A bright autumn day with falling leaves",
     "A happy family enjoying a day at the park",
     "A cheerful snowman with a carrot nose",
     "A playful kitten chasing a ball of yarn",
     "A colorful garden full of flowers",
     "A joyful beach day with surfboards",
     "A bright sun shining over the ocean",
     "A happy child riding a bike on a trail",
     "A whimsical butterfly dancing in the breeze",
     "A cheerful picnic scene with delicious food",
     "A playful seal juggling beach balls",
     "A joyful family playing games on a picnic",
     "A colorful sunset with silhouettes of trees",
     "A happy dog playing in a snowfield",
     "A bright flower garden with buzzing bees",
     "A whimsical fairy tale castle in the sky",
     "A cheerful parrot perched on a swing",
     "A playful kitten exploring a cardboard box",
     "A bright rainbow stretching across the sky",
     "A joyful family celebrating a birthday",
     "A cozy cabin in a snowy landscape",
     "A happy penguin sliding on ice",
     "A cheerful garden with colorful flowers",
     "A playful otter swimming with friends",
     "A bright and sunny meadow with wildflowers",
     "A joyful child blowing bubbles in the park",
     "A whimsical snail with a decorated shell",
     "A colorful hot air balloon floating in the air",
     "A cheerful family on a camping trip",
     "A happy sunflower smiling at the sun",
     "A playful puppy rolling in the grass",
     "A bright star shining in the night sky",
     "A joyful girl dancing in a flower field",
     "A whimsical gnome garden with colorful flowers",
     "A cheerful cat lounging in a sunbeam",
     "A playful dolphin swimming with fish",
     "A colorful fruit tree in a sunny garden",
     "A bright and happy scene at a fair",
     "A joyful family playing in the snow",
     "A whimsical unicorn prancing in a meadow",
     "A cheerful girl skipping through a field",
     "A bright butterfly fluttering among flowers",
     "A happy dog enjoying a sunny day at the park",
     "A colorful rainbow stretching over a mountain",
     "A joyful child painting a colorful picture",
     "A playful kitten pouncing on a ball",
     "A cheerful sun shining over a playground",
     "A bright and sunny garden with hummingbirds",
     "A happy couple sharing ice cream on a date",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing catch with a dog",
     "A cozy blanket fort filled with pillows",
     "A cheerful snowman wearing a hat and scarf",
     "A bright flower bouquet with a happy smiley face",
     "A playful baby seal in the ocean",
     "A colorful kite flying high in the sky",
     "A joyful day at the amusement park",
     "A cheerful ladybug crawling on a leaf",
     "A happy child exploring a nature trail",
     "A whimsical village with colorful houses",
     "A bright rainbow after a summer rain",
     "A playful kitten cuddling with a puppy",
     "A cheerful sun peeking through the trees",
     "A joyful picnic on a sunny day",
     "A colorful carnival with rides and games",
     "A happy family building a sandcastle",
     "A whimsical tree with owls sitting on branches",
     "A bright blue sky with a few fluffy clouds",
     "A joyful child catching fireflies at night",
     "A cozy living room with a crackling fire",
     "A cheerful gnome with a red hat",
     "A playful dolphin leaping through the waves",
     "A bright flower field buzzing with bees",
     "A joyful child exploring a pumpkin patch",
     "A whimsical fairy flying over a flower garden",
     "A cheerful sun shining over a farm",
     "A happy dog playing in a field of flowers",
     "A colorful kite festival in the sky",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining down on a forest",
     "A joyful family playing in a leaf pile",
     "A whimsical treehouse with a slide",
     "A cheerful snowman waving hello",
     "A bright garden full of blooming flowers",
     "A happy couple enjoying a picnic",
     "A playful seal swimming with dolphins",
     "A joyful day at the beach with friends",
     "A whimsical castle with a dragon flying above",
     "A cheerful elephant playing with a beach ball",
     "A bright flower crown on a girl's head",
     "A playful kitten sleeping in a basket",
     "A colorful parrot perched on a branch",
     "A joyful girl holding a bunch of balloons",
     "A cheerful family building a snowman",
     "A bright autumn day with colorful leaves",
     "A happy dog chasing its tail",
     "A whimsical butterfly landing on a flower",
     "A cozy cabin in the snowy mountains",
     "A joyful family enjoying a game night",
     "A cheerful sun smiling down on a picnic",
     "A playful dolphin leaping out of the water",
     "A bright rainbow with a pot of gold",
     "A happy penguin waddling on ice",
     "A colorful garden filled with fruits and vegetables",
     "A joyful child playing dress-up",
     "A whimsical fairy tale forest",
     "A cheerful family on a road trip",
     "A bright sunny day at the park",
     "A playful kitten chasing after butterflies",
     "A joyful child playing in a flower garden",
     "A whimsical castle on a cloud",
     "A cheerful ladybug crawling on a flower petal",
     "A bright sun shining over a meadow",
     "A happy dog enjoying a day at the beach",
     "A colorful butterfly landing on a child's finger",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting on a mushroom",
     "A playful rabbit in a flower field",
     "A bright blue sky with a rainbow",
     "A joyful girl dancing with a friend",
     "A whimsical fish swimming in a coral reef",
     "A happy child building a snow fort",
     "A cheerful flower garden with buzzing bees",
     "A bright sunny day with fluffy clouds",
     "A playful seal sliding down a snowy hill",
     "A joyful family at a picnic table",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple walking hand in hand",
     "A whimsical fairy dancing on a flower petal",
     "A joyful puppy exploring a new place",
     "A bright rainbow over a sparkling lake",
     "A cheerful snowman holding a sign",
     "A playful dolphin jumping through a hoop",
     "A joyful day at the zoo with friends",
     "A colorful kite floating in the breeze",
     "A happy child riding a bike down a hill",
     "A whimsical unicorn grazing in a meadow",
     "A cheerful garden full of sunflowers",
     "A playful kitten chasing a feather toy",
     "A bright star shining in the evening sky",
     "A joyful family enjoying a movie night at home",
     "A whimsical castle with a drawbridge",
     "A cheerful snowflake sparkling in the sun",
     "A playful puppy running in a field",
     "A bright sunny day with birds chirping",
     "A happy child playing hopscotch on the sidewalk",
     "A cheerful tree with colorful leaves",
     "A whimsical garden filled with fairies",
     "A joyful girl skipping through a flower patch",
     "A bright butterfly fluttering in the air",
     "A playful dolphin swimming with friends",
     "A cheerful family gathering for a holiday meal",
     "A joyful day at the amusement park with rides",
     "A colorful balloon floating in the sky",
     "A happy dog rolling in the grass",
     "A whimsical castle on a hill",
     "A bright flower field under a clear blue sky",
     "A joyful family making a gingerbread house",
     "A cheerful sun peeking through the clouds",
     "A playful seal balancing a beach ball",
     "A bright rainbow arching over the mountains",
     "A happy child playing with a puppy",
     "A whimsical fairy flying among the flowers",
     "A joyful day at the beach with sandcastles",
     "A colorful fruit tree in a sunny garden",
     "A cheerful family enjoying a picnic in the park",
     "A playful otter sliding on a water slide",
     "A bright and sunny day with children playing",
     "A joyful puppy wagging its tail",
     "A whimsical treehouse with a rope ladder",
     "A cheerful snowman with a button nose",
     "A happy couple sharing a sundae",
     "A playful dolphin leaping out of the water",
     "A bright star shining down on a cozy home",
     "A joyful child playing in the rain",
     "A whimsical butterfly resting on a flower",
     "A cheerful family hiking in the mountains",
     "A happy dog exploring a new trail",
     "A colorful garden filled with blooming flowers",
     "A joyful child enjoying a sunny day",
     "A whimsical unicorn prancing through a meadow",
     "A bright blue sky with a few clouds",
     "A cheerful sun smiling over a playground",
     "A playful rabbit hopping through the grass",
     "A bright rainbow after a rain shower",
     "A joyful family baking a cake together",
     "A colorful village with happy people",
     "A happy child with a balloon",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright flower crown on a happy girl",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy flying through a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
"A bright sun smiling in the sky",
     "Colorful flowers blooming in a field",
     "A serene beach with gentle waves",
     "A cozy cabin in the woods",
     "A rainbow after a light rain",
     "A whimsical treehouse",
     "A garden full of butterflies",
     "A peaceful lake with ducks",
     "A mountain landscape at sunrise",
     "A vibrant sunset over the ocean",
     "A field of sunflowers facing the sun",
     "A cozy campfire surrounded by trees",
     "A snowy landscape with a snowman",
     "A cherry blossom tree in full bloom",
     "A playful puppy in a grassy field",
     "A kite flying high in the sky",
     "A gentle waterfall in a forest",
     "A whimsical mushroom village",
     "A hot air balloon festival",
     "A cozy picnic setup in the park",
     "A smiling cat playing with yarn",
     "A happy dog wagging its tail",
     "A cute bunny hopping through the grass",
     "A cheerful penguin sliding on ice",
     "A colorful parrot sitting on a branch",
     "A friendly dolphin jumping in the ocean",
     "A playful kitten chasing a butterfly",
     "A cartoonish elephant spraying water",
     "A flock of cheerful birds in the sky",
     "A cuddly teddy bear with a big smile",
     "A happy squirrel gathering acorns",
     "A lazy sloth hanging from a tree",
     "A baby deer peeking through bushes",
     "A family of turtles sunbathing on a rock",
     "A dancing fox in a forest clearing",
     "A cheerful ladybug on a leaf",
     "A playful seal balancing a ball",
     "A group of friendly fish swimming together",
     "A colorful snail with a shiny shell",
     "A happy hedgehog with flowers",
     "A joyful raccoon exploring a garden",
     "A whimsical owl wearing glasses",
     "A cartoon whale splashing in the sea",
     "A fluffy alpaca with a colorful scarf",
     "A friendly crab waving on the beach",
     "A bright rainbow fish swimming in a pond",
     "A singing frog on a lily pad",
     "A pair of lovebirds in a tree",
     "A tiny mouse holding a piece of cheese",
     "A happy goat on a grassy hill",
     "A whimsical unicorn in a magical forest",
     "A cute fox peeking out from behind a tree",
     "A playful puppy in a field of flowers",
     "A cheerful baby elephant spraying water",
     "A colorful butterfly resting on a flower",
     "A whimsical dragon flying in the sky",
     "A happy kangaroo with a baby in its pouch",
     "A joyful otter floating on its back",
     "A family of ducks waddling by a pond",
     "A smiling sun with sunglasses",
     "A friendly monster with big eyes",
     "A cartoon bear holding a honey pot",
     "A cheerful chipmunk with acorns",
     "A colorful iguana on a branch",
     "A dancing parrot on a tropical island",
     "A group of children playing in a park",
     "A whimsical tree with smiling faces",
     "A magical fairy sitting on a mushroom",
     "A cheerful snowman with a carrot nose",
     "A bright yellow taxi in a busy city",
     "A cozy coffee shop with happy customers",
     "A peaceful village with colorful houses",
     "A happy family having a barbecue",
     "A rainbow-colored bicycle by a park",
     "A serene hammock between two palm trees",
     "A joyful girl flying a kite",
     "A colorful carousel with happy children",
     "A sunny day at the amusement park",
     "A friendly giant with a big smile",
     "A cheerful flower shop bursting with colors",
     "A colorful market with fresh fruits",
     "A bright red barn on a sunny day",
     "A happy ice cream truck parked in a park",
     "A smiling chef with a giant cupcake",
     "A cheerful panda eating bamboo",
     "A playful otter in a sparkling river",
     "A sunny garden with blooming daisies",
     "A whimsical hot air balloon floating in the sky",
     "A playful raccoon digging through a trash can",
     "A happy bear hugging a tree",
     "A colorful kite festival in the park",
     "A bright and sunny day at the beach",
     "A playful dolphin jumping through waves",
     "A friendly cat lounging in a sunny window",
     "A cheerful snowflake dancing in the air",
     "A cozy blanket fort with fairy lights",
     "A happy snail leaving a colorful trail",
     "A sunny day in a flower garden",
     "A whimsical castle in the clouds",
     "A friendly robot waving hello",
     "A joyful puppy playing in the rain",
     "A bright and colorful paint palette",
     "A group of children building a sandcastle",
     "A cheerful birdhouse in a tree",
     "A happy family on a picnic",
     "A whimsical village with quirky houses",
     "A colorful jigsaw puzzle in progress",
     "A smiling planet with rings",
     "A cozy reading nook with plush pillows",
     "A playful kitten in a box",
     "A bright sunflower turning towards the sun",
     "A magical garden with glowing plants",
     "A happy bear fishing in a stream",
     "A joyful celebration with balloons and confetti",
     "A bright orange sunset over the mountains",
     "A cheerful gingerbread house",
     "A whimsical circus with happy performers",
     "A colorful rainbow stretching across the sky",
     "A playful puppy chasing a butterfly",
     "A smiling cupcake with sprinkles",
     "A group of friends dancing at a party",
     "A happy cat lounging on a windowsill",
     "A vibrant fruit bowl overflowing with colors",
     "A bright beach umbrella on a sunny day",
     "A whimsical snow globe with a winter scene",
     "A cozy fireplace with happy family moments",
     "A cheerful pumpkin in a patch",
     "A bright flower crown on a girl's head",
     "A happy little gnome in a garden",
     "A joyful raccoon at a campsite",
     "A colorful peacock displaying its feathers",
     "A serene park with children playing",
     "A smiling frog playing a guitar",
     "A happy chef in a busy kitchen",
     "A whimsical windmill in a sunny field",
     "A cheerful owl perched on a tree branch",
     "A colorful train traveling through the countryside",
     "A playful monkey swinging from vines",
     "A happy baby riding a bicycle",
     "A cozy blanket and a cup of tea",
     "A bright rainbow stretching over a field",
     "A happy family portrait in a park",
     "A joyful girl dancing in a flower field",
     "A colorful fruit stand at a market",
     "A smiling whale swimming in the ocean",
     "A playful sea turtle swimming among coral",
     "A cheerful farmer in a field of crops",
     "A bright and colorful flower bouquet",
     "A joyful family playing games together",
     "A sunny day at a fair with rides",
     "A cheerful sun peeking through the clouds",
     "A playful dolphin painting in the sea",
     "A bright ice cream cone on a hot day",
     "A cozy blanket and a good book",
     "A whimsical fairy flying among flowers",
     "A cheerful sun and moon in the sky",
     "A happy dog playing fetch",
     "A colorful sunset over a city skyline",
     "A joyful girl spinning in a flower field",
     "A whimsical castle with colorful flags",
     "A playful puppy in a pile of leaves",
     "A bright and happy playground",
     "A cheerful ginger cat sleeping on a porch",
     "A sunny park with children playing tag",
     "A cozy tea party with stuffed animals",
     "A bright butterfly landing on a flower",
     "A happy snowman wearing a scarf",
     "A joyful dance party with friends",
     "A colorful peacock in a sunny garden",
     "A playful panda climbing a tree",
     "A cheerful elephant spraying water",
     "A bright starry night sky",
     "A happy garden with bees buzzing",
     "A cozy cabin with smoke coming from the chimney",
     "A playful puppy digging in the sand",
     "A whimsical fairy tale book with illustrations",
     "A joyful child jumping in puddles",
     "A colorful sailboat on a sunny day",
     "A cheerful penguin sliding on snow",
     "A bright yellow sun with happy rays",
     "A happy group of kids playing soccer",
     "A whimsical lighthouse by the sea",
     "A joyful puppy wagging its tail",
     "A colorful dragonfly buzzing around",
     "A happy baby playing with blocks",
     "A cheerful flower garden in spring",
     "A bright and sunny farmer's market",
     "A joyful child playing in a fountain",
     "A cozy home with a welcome mat",
     "A playful dolphin jumping through a hoop",
     "A cheerful hedgehog exploring a garden",
     "A bright and sunny hillside",
     "A happy cat chasing its tail",
     "A whimsical mushroom house",
     "A joyful picnic in a meadow",
     "A colorful birdhouse with birds",
     "A cheerful fox in a flower field",
     "A happy kid riding a scooter",
     "A bright rainbow arching over hills",
     "A playful seal balancing a ball on its nose",
     "A whimsical jellyfish floating in the sea",
     "A joyful family playing catch in the park",
     "A sunny day with children riding bikes",
     "A colorful paper airplane flying through the sky",
     "A cheerful whale breaching the ocean surface",
     "A happy squirrel munching on a nut",
     "A cozy reading corner with soft pillows",
     "A bright blue sky with fluffy clouds",
     "A joyful child blowing bubbles",
     "A whimsical fairy dancing in the moonlight",
     "A happy sunflower with a smiley face",
     "A playful otter sliding down a hill",
     "A bright and colorful fireworks display",
     "A cheerful girl dancing in the rain",
     "A happy family at a birthday party",
     "A colorful picnic blanket with food",
     "A joyful parrot singing on a branch",
     "A bright kite flying in a clear sky",
     "A playful kitten in a ball of yarn",
     "A cheerful sun shining over a park",
     "A whimsical carousel with happy animals",
     "A happy dog sticking its head out of a car window",
     "A colorful birthday cake with candles",
     "A joyful child making a sandcastle",
     "A cozy home with a garden",
     "A bright hot air balloon in the sky",
     "A playful rabbit hopping in a meadow",
     "A cheerful family enjoying a movie night",
     "A happy child feeding ducks at a pond",
     "A whimsical fairy house in the woods",
     "A bright flower pot on a windowsill",
     "A joyful girl twirling in a dress",
     "A cheerful garden gnome in a flower bed",
     "A happy snowman with a carrot nose and scarf",
     "A colorful candy shop filled with treats",
     "A playful puppy chasing after a ball",
     "A bright and sunny day at the zoo",
     "A joyful child playing in a leaf pile",
     "A whimsical pirate ship sailing the seas",
     "A happy family hiking on a sunny day",
     "A colorful village with balloons in the sky",
     "A cheerful frog leaping on lily pads",
     "A bright flower crown on a girl's head",
     "A joyful beach day with surfboards",
     "A cozy winter cabin with lights",
     "A playful kitten playing with a feather",
     "A cheerful tree with colorful leaves",
     "A bright and sunny day with butterflies",
     "A happy couple enjoying a sunset",
     "A whimsical fish swimming in a bubble",
     "A joyful dog jumping through hoops",
     "A colorful candy cane forest",
     "A bright and cheerful ice cream parlor",
     "A happy dog enjoying a sunny day",
     "A whimsical fox peeking out from behind a bush",
     "A colorful painting palette with brushes",
     "A cheerful rainbow with a pot of gold",
     "A happy family making a snowman",
     "A bright garden with vegetables growing",
     "A joyful girl flying a colorful kite",
     "A whimsical snail with a patterned shell",
     "A cheerful elephant spraying water",
     "A playful raccoon climbing a tree",
     "A colorful butterfly fluttering by",
     "A bright and happy farm scene",
     "A joyful picnic under a shady tree",
     "A cozy living room with happy moments",
     "A cheerful hot air balloon festival",
     "A happy child playing hopscotch",
     "A whimsical dragon flying through clouds",
     "A colorful paper crane flying in the wind",
     "A joyful puppy playing with a friend",
     "A bright sun shining over a field",
     "A happy child drawing with chalk",
     "A cheerful baby duckling waddling",
     "A cozy kitchen filled with baked goods",
     "A whimsical treehouse in a sunny park",
     "A joyful family decorating a Christmas tree",
     "A bright garden filled with bees",
     "A playful dolphin splashing in the ocean",
     "A cheerful scarecrow in a field",
     "A colorful playground filled with kids",
     "A happy monkey swinging from a tree",
     "A whimsical fairy flying among flowers",
     "A joyful puppy exploring a garden",
     "A bright rainbow with smiling clouds",
     "A happy child dancing in the rain",
     "A cheerful giraffe reaching for leaves",
     "A playful kitten playing with a butterfly",
     "A bright and sunny picnic scene",
     "A whimsical elephant playing in a puddle",
     "A joyful day at the beach with friends",
     "A cozy corner with plants and sunlight",
     "A cheerful flower arrangement in a vase",
     "A bright blue bird sitting on a branch",
     "A playful bear catching fish in a river",
     "A colorful jigsaw puzzle of a happy scene",
     "A joyful child running through a field",
     "A whimsical castle in a sunny landscape",
     "A bright star shining in the night sky",
     "A happy child painting a picture",
     "A cheerful ladybug on a leaf",
     "A colorful fish swimming in clear water",
     "A playful otter floating in a river",
     "A joyful family playing board games",
     "A bright balloon floating in the sky",
     "A happy cat chasing a string",
     "A whimsical tree with hanging lanterns",
     "A cheerful snowflake falling from the sky",
     "A playful seal balancing a fish",
     "A colorful flower field under a blue sky",
     "A joyful girl spinning with her arms open",
     "A bright and happy butterfly garden",
     "A happy dog running through tall grass",
     "A whimsical birdhouse with birds singing",
     "A cheerful painting of a sunny day",
     "A cozy coffee shop filled with laughter",
     "A playful rabbit in a vegetable garden",
     "A bright sun illuminating a forest",
     "A joyful family dancing together",
     "A colorful festival with lights and decorations",
     "A happy girl wearing a flower crown",
     "A cheerful elephant splashing water in a river",
     "A whimsical night sky filled with stars",
     "A playful kitten hiding in a box",
     "A bright rainbow arching over the hills",
     "A joyful child exploring a flower garden",
     "A cozy home with a warm fireplace",
     "A happy family enjoying a day at the zoo",
     "A cheerful snowman with a scarf and hat",
     "A colorful beach scene with umbrellas",
     "A playful dolphin jumping through waves",
     "A joyful family decorating a gingerbread house",
     "A whimsical fairy flying over a pond",
     "A bright and sunny garden with butterflies",
     "A happy dog catching a frisbee",
     "A cheerful child playing with a puppy",
     "A whimsical castle with a rainbow bridge",
     "A joyful family having a barbecue in the backyard",
     "A bright autumn day with falling leaves",
     "A happy family enjoying a day at the park",
     "A cheerful snowman with a carrot nose",
     "A playful kitten chasing a ball of yarn",
     "A colorful garden full of flowers",
     "A joyful beach day with surfboards",
     "A bright sun shining over the ocean",
     "A happy child riding a bike on a trail",
     "A whimsical butterfly dancing in the breeze",
     "A cheerful picnic scene with delicious food",
     "A playful seal juggling beach balls",
     "A joyful family playing games on a picnic",
     "A colorful sunset with silhouettes of trees",
     "A happy dog playing in a snowfield",
     "A bright flower garden with buzzing bees",
     "A whimsical fairy tale castle in the sky",
     "A cheerful parrot perched on a swing",
     "A playful kitten exploring a cardboard box",
     "A bright rainbow stretching across the sky",
     "A joyful family celebrating a birthday",
     "A cozy cabin in a snowy landscape",
     "A happy penguin sliding on ice",
     "A cheerful garden with colorful flowers",
     "A playful otter swimming with friends",
     "A bright and sunny meadow with wildflowers",
     "A joyful child blowing bubbles in the park",
     "A whimsical snail with a decorated shell",
     "A colorful hot air balloon floating in the air",
     "A cheerful family on a camping trip",
     "A happy sunflower smiling at the sun",
     "A playful puppy rolling in the grass",
     "A bright star shining in the night sky",
     "A joyful girl dancing in a flower field",
     "A whimsical gnome garden with colorful flowers",
     "A cheerful cat lounging in a sunbeam",
     "A playful dolphin swimming with fish",
     "A colorful fruit tree in a sunny garden",
     "A bright and happy scene at a fair",
     "A joyful family playing in the snow",
     "A whimsical unicorn prancing in a meadow",
     "A cheerful girl skipping through a field",
     "A bright butterfly fluttering among flowers",
     "A happy dog enjoying a sunny day at the park",
     "A colorful rainbow stretching over a mountain",
     "A joyful child painting a colorful picture",
     "A playful kitten pouncing on a ball",
     "A cheerful sun shining over a playground",
     "A bright and sunny garden with hummingbirds",
     "A happy couple sharing ice cream on a date",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing catch with a dog",
     "A cozy blanket fort filled with pillows",
     "A cheerful snowman wearing a hat and scarf",
     "A bright flower bouquet with a happy smiley face",
     "A playful baby seal in the ocean",
     "A colorful kite flying high in the sky",
     "A joyful day at the amusement park",
     "A cheerful ladybug crawling on a leaf",
     "A happy child exploring a nature trail",
     "A whimsical village with colorful houses",
     "A bright rainbow after a summer rain",
     "A playful kitten cuddling with a puppy",
     "A cheerful sun peeking through the trees",
     "A joyful picnic on a sunny day",
     "A colorful carnival with rides and games",
     "A happy family building a sandcastle",
     "A whimsical tree with owls sitting on branches",
     "A bright blue sky with a few fluffy clouds",
     "A joyful child catching fireflies at night",
     "A cozy living room with a crackling fire",
     "A cheerful gnome with a red hat",
     "A playful dolphin leaping through the waves",
     "A bright flower field buzzing with bees",
     "A joyful child exploring a pumpkin patch",
     "A whimsical fairy flying over a flower garden",
     "A cheerful sun shining over a farm",
     "A happy dog playing in a field of flowers",
     "A colorful kite festival in the sky",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining down on a forest",
     "A joyful family playing in a leaf pile",
     "A whimsical treehouse with a slide",
     "A cheerful snowman waving hello",
     "A bright garden full of blooming flowers",
     "A happy couple enjoying a picnic",
     "A playful seal swimming with dolphins",
     "A joyful day at the beach with friends",
     "A whimsical castle with a dragon flying above",
     "A cheerful elephant playing with a beach ball",
     "A bright flower crown on a girl's head",
     "A playful kitten sleeping in a basket",
     "A colorful parrot perched on a branch",
     "A joyful girl holding a bunch of balloons",
     "A cheerful family building a snowman",
     "A bright autumn day with colorful leaves",
     "A happy dog chasing its tail",
     "A whimsical butterfly landing on a flower",
     "A cozy cabin in the snowy mountains",
     "A joyful family enjoying a game night",
     "A cheerful sun smiling down on a picnic",
     "A playful dolphin leaping out of the water",
     "A bright rainbow with a pot of gold",
     "A happy penguin waddling on ice",
     "A colorful garden filled with fruits and vegetables",
     "A joyful child playing dress-up",
     "A whimsical fairy tale forest",
     "A cheerful family on a road trip",
     "A bright sunny day at the park",
     "A playful kitten chasing after butterflies",
     "A joyful child playing in a flower garden",
     "A whimsical castle on a cloud",
     "A cheerful ladybug crawling on a flower petal",
     "A bright sun shining over a meadow",
     "A happy dog enjoying a day at the beach",
     "A colorful butterfly landing on a child's finger",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting on a mushroom",
     "A playful rabbit in a flower field",
     "A bright blue sky with a rainbow",
     "A joyful girl dancing with a friend",
     "A whimsical fish swimming in a coral reef",
     "A happy child building a snow fort",
     "A cheerful flower garden with buzzing bees",
     "A bright sunny day with fluffy clouds",
     "A playful seal sliding down a snowy hill",
     "A joyful family at a picnic table",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple walking hand in hand",
     "A whimsical fairy dancing on a flower petal",
     "A joyful puppy exploring a new place",
     "A bright rainbow over a sparkling lake",
     "A cheerful snowman holding a sign",
     "A playful dolphin jumping through a hoop",
     "A joyful day at the zoo with friends",
     "A colorful kite floating in the breeze",
     "A happy child riding a bike down a hill",
     "A whimsical unicorn grazing in a meadow",
     "A cheerful garden full of sunflowers",
     "A playful kitten chasing a feather toy",
     "A bright star shining in the evening sky",
     "A joyful family enjoying a movie night at home",
     "A whimsical castle with a drawbridge",
     "A cheerful snowflake sparkling in the sun",
     "A playful puppy running in a field",
     "A bright sunny day with birds chirping",
     "A happy child playing hopscotch on the sidewalk",
     "A cheerful tree with colorful leaves",
     "A whimsical garden filled with fairies",
     "A joyful girl skipping through a flower patch",
     "A bright butterfly fluttering in the air",
     "A playful dolphin swimming with friends",
     "A cheerful family gathering for a holiday meal",
     "A joyful day at the amusement park with rides",
     "A colorful balloon floating in the sky",
     "A happy dog rolling in the grass",
     "A whimsical castle on a hill",
     "A bright flower field under a clear blue sky",
     "A joyful family making a gingerbread house",
     "A cheerful sun peeking through the clouds",
     "A playful seal balancing a beach ball",
     "A bright rainbow arching over the mountains",
     "A happy child playing with a puppy",
     "A whimsical fairy flying among the flowers",
     "A joyful day at the beach with sandcastles",
     "A colorful fruit tree in a sunny garden",
     "A cheerful family enjoying a picnic in the park",
     "A playful otter sliding on a water slide",
     "A bright and sunny day with children playing",
     "A joyful puppy wagging its tail",
     "A whimsical treehouse with a rope ladder",
     "A cheerful snowman with a button nose",
     "A happy couple sharing a sundae",
     "A playful dolphin leaping out of the water",
     "A bright star shining down on a cozy home",
     "A joyful child playing in the rain",
     "A whimsical butterfly resting on a flower",
     "A cheerful family hiking in the mountains",
     "A happy dog exploring a new trail",
     "A colorful garden filled with blooming flowers",
     "A joyful child enjoying a sunny day",
     "A whimsical unicorn prancing through a meadow",
     "A bright blue sky with a few clouds",
     "A cheerful sun smiling over a playground",
     "A playful rabbit hopping through the grass",
     "A bright rainbow after a rain shower",
     "A joyful family baking a cake together",
     "A colorful village with happy people",
     "A happy child with a balloon",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright flower crown on a happy girl",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy flying through a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",
     "A cheerful garden filled with laughter",
     "A joyful day at the zoo with friends",
     "A bright blue sky with fluffy clouds",
     "A happy dog wagging its tail in the park",
     "A whimsical treehouse with a rope swing",
     "A colorful butterfly landing on a flower petal",
     "A joyful family baking cookies together",
     "A cheerful gnome sitting in a garden",
     "A playful rabbit hopping in a sunny meadow",
     "A bright star shining in the evening sky",
     "A joyful girl dancing with her friends",
     "A whimsical fairy tale forest filled with magic",
     "A happy child playing in the rain",
     "A colorful village with joyful people",
     "A cheerful sun peeking through the trees",
     "A playful dolphin jumping through a hoop",
     "A joyful family gathering around a bonfire",
     "A bright rainbow arching over a river",
     "A cheerful snowman holding a candy cane",
     "A happy couple walking hand in hand",
     "A whimsical fairy flying in a garden",
     "A bright sunny day with children playing outside",
     "A joyful puppy wagging its tail",
     "A playful kitten chasing a string",
     "A colorful garden full of sunflowers",
     "A cheerful child enjoying a sunny day",
     "A whimsical castle surrounded by flowers",
     "A joyful day at the amusement park with rides",
     "A happy child with a balloon",
     "A bright blue sky with a few fluffy clouds",
     "A cheerful gnome waving hello",
     "A playful dolphin swimming with friends",
     "A joyful family having a picnic in the park",
     "A colorful kite floating in the sky",
     "A happy dog playing in a field of flowers",
     "A whimsical fairy tale cottage in the woods",
     "A cheerful garden filled with laughter and love",
     "A bright flower crown on a happy girl",
     "A playful seal sliding on ice",
     "A joyful day at the beach with family",
     "A bright and sunny day with children playing",
     "A whimsical dragon flying over a valley",
     "A cheerful family decorating their home for the holidays",
     "A bright sunny day with laughter",
     "A joyful puppy playing with a child",
     "A whimsical tree with a swing",
     "A colorful garden with butterflies fluttering by",
     "A happy dog running through a field of flowers",
     "A playful dolphin swimming in the ocean",
     "A cheerful gnome waving hello",
     "A bright sun shining over a picnic table",
     "A joyful family enjoying a board game night",
     "A whimsical fairy dancing in a garden",
     "A cheerful child playing with a kite",
     "A bright rainbow over a blue sky",
     "A happy penguin waddling through the snow",
     "A colorful hot air balloon festival in the sky",
     "A joyful day at the zoo with family",
     "A playful kitten exploring a new toy",
     "A cheerful elephant splashing in a puddle",
     "A bright flower garden with buzzing bees",
     "A whimsical castle with a drawbridge",
     "A joyful family decorating a Christmas tree",
     "A happy child flying a kite in the park",
     "A cheerful sun shining down on a playground",
     "A colorful fruit stand filled with fresh produce",
     "A playful dolphin leaping through a wave",
     "A joyful child playing tag with friends",
     "A bright rainbow after a summer storm",
     "A cheerful ladybug resting on a leaf",
     "A whimsical fairy dancing in a meadow",
     "A happy dog playing fetch in a park",
     "A colorful garden full of flowers",
     "A joyful family enjoying a barbecue together",
     "A bright sunny day with children playing",
     "A playful seal balancing a ball on its nose",
     "A whimsical village with happy animals",
     "A cheerful child building a sandcastle",
     "A happy couple dancing at sunset",
     "A colorful kite flying in the sky",
     "A joyful day at the amusement park with rides",
     "A bright star shining in the night sky",
     "A playful rabbit hopping through a flower garden",
     "A cheerful snowman with a carrot nose and scarf",
     "A joyful family enjoying a picnic at the park",
     "A colorful balloon floating in the air",
     "A happy dog running through a field of flowers",
     "A whimsical fairy tale castle in the clouds",
     "A bright and sunny day with butterflies",
     "A cheerful parrot perched on a branch",
     "A playful dolphin swimming with a friend",
     "A joyful day at the beach with sandcastles",
     "A colorful garden filled with fruits and vegetables",
     "A happy child riding a bike in the park",
     "A whimsical butterfly fluttering around flowers",
     "A cheerful family on a camping trip",
     "A bright rainbow arching over a sunny meadow",
     "A playful seal sliding down a snowy hill",
     "A joyful child exploring a pumpkin patch",
     "A colorful festival with lights and music",
     "A cheerful sun shining over a beach",
     "A happy couple sharing a sundae",
     "A whimsical dragon flying in the clouds",
     "A joyful family playing games in the park",
     "A bright flower crown on a girl's head",
     "A playful kitten chasing after a butterfly",

    ];
    const randomIndex = Math.floor(Math.random() * prompts.length);
    setCurrentPrompt(prompts[randomIndex]);
  };
  useEffect(() => {
    const getUserId = async () => {
      try {
        const storedUserId = await AsyncStorage.getItem('userID');
        console.log('Stored User ID:', storedUserId); // Log the retrieved User ID
        if (storedUserId) {
          setUserId(storedUserId);
        }
      } catch (error) {
        console.error('Failed to load user ID', error);
      }
    };

    getUserId();
  }, []);

  const saveToGallery = async () => {
    if (paintRef.current) {
      try {
        // Capture the painting as a PNG
        const uri = await captureRef(paintRef, {
          format: 'png',
          quality: 1,
        });
  
        // Log the image data for debugging
        console.log("Image URI:", uri);
  
        // Step 1: Fetch the current coins to increment by 10
        const { data: userData, error: fetchError } = await supabase
          .from('profiles')
          .select('coins') // Get the current coins value
          .eq('id', userID)
          .single(); // Get a single user record
  
        if (fetchError) {
          console.error('Error fetching user coins:', fetchError);
          Alert.alert('Error', 'Failed to fetch user coins.');
          return; // Exit if there's an error
        }
  
        // Increment coins by 10
        const newCoinsValue = (userData.coins || 0) + 10;
  
        // Step 2: Update the user's painting data and coins in Supabase
        const { data, error } = await supabase
          .from('profiles') // Ensure this is the correct table name
          .update({
            paint_data: uri, // Store the image data in the paint_data column
            coins: newCoinsValue // Set the updated coins value
          })
          .eq('id', userID); // Ensure userID is valid
  
        // Step 3: Handle potential errors or success
        if (error) {
          console.error('Error saving image to Supabase:', error);
          Alert.alert('Error', 'Failed to save the image to Supabase.');
        } else {
          console.log('Painting saved successfully:', data);
          Alert.alert('Success', 'Painting saved and coins updated!');
        }
  
      } catch (error) {
        console.error('Error saving image to gallery:', error);
        Alert.alert('Error', 'Failed to save the image to the gallery.');
      }
    }
  };
  
  

  const saveToCameraRoll = async () => {
    if (paintRef.current) {
      try {
        const uri = await captureRef(paintRef, {
          format: 'png',
          quality: 1,
        });
        const asset = await MediaLibrary.createAssetAsync(uri);
        Alert.alert('Success', 'Painting saved to Camera Roll!');
      } catch (error) {
        console.error('Error saving to camera roll:', error);
        Alert.alert('Error', 'Failed to save the image to Camera Roll.');
      }
    }
  };

  // New function to clear the grid
  const clearGrid = () => {
    setGrid(Array(gridSize).fill(null)); // Reset grid to initial state
  };

  const cellSize = maxGridWidth / columns; // Calculate size based on max grid width
  const gridStyle = {
    flexDirection: 'row',
    flexWrap: 'wrap',
    maxWidth: maxGridWidth, // Set the maximum width of the grid
    margin: gridMargin, // Center the grid with margin
  };

  return (
    <View style={styles.container}>
      <View style={styles.homeButton}>
        <TouchableOpacity onPress={handleHomePress}>
          <Image source={require("../screen/assets/home.png")} style={styles.home} />
        </TouchableOpacity>
      </View>
      <Header 
        text={headerText}
        onSettingsPress={() => navigation.navigate('Settings')} 
        iconColor="#FFFFFF"
        textColor="#FFFFFF"
      />
      <View style={styles.colorPalette}>
        {colors.map((color, index) => (
          <TouchableOpacity
            key={index}
            style={[styles.colorBox, { backgroundColor: color, width: cellSize, height: cellSize, borderColor: '#FFFFFF' }]} // White outline for color boxes
            onPress={() => setSelectedColor(color)}
          />
        ))}
      </View>
      <TouchableOpacity style={styles.replaceColorButton} onPress={replaceRandomColor}>
        <Text style={styles.replaceColorButtonText}>Replace Random Color</Text>
      </TouchableOpacity>
      <View ref={paintRef} style={gridStyle}>
        {grid.map((color, index) => (
          <TouchableOpacity
            key={index}
            style={[styles.cell, { backgroundColor: color || '#FFFFFF', width: cellSize, height: cellSize, borderColor: '#000000' }]} // Black outline for each cell
            onPress={() => handleCellPress(index)}
          />
        ))}
      </View>
      <TouchableOpacity style={styles.promptButton} onPress={pickRandomPrompt}>
        <Text style={styles.promptButtonText}>Get a Prompt</Text>
      </TouchableOpacity>
      {currentPrompt && <Text style={styles.promptText}>{currentPrompt}</Text>}
      <TouchableOpacity style={styles.saveButton} onPress={saveToGallery}>
        <Text style={styles.saveButtonText}>Save to Gallery</Text>
      </TouchableOpacity>
      <TouchableOpacity style={styles.saveButton} onPress={saveToCameraRoll}>
        <Text style={styles.saveButtonText}>Save to Camera Roll</Text>
      </TouchableOpacity>
      {/* New Clear Button */}
      <TouchableOpacity style={styles.clearButton} onPress={clearGrid}>
        <Text style={styles.clearButtonText}>Clear</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#213D61',
  },
  homeButton: {
    position: 'absolute',
    top: '6%', 
    right: '5%', 
    zIndex: 10,
  },
  home: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  colorPalette: {
    flexDirection: 'row',
    marginBottom: 20,
    marginTop: '10%',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  colorBox: {
    margin: 5,
    borderWidth: 2, // Add border width
  },
  replaceColorButton: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 5,
  },
  replaceColorButtonText: {
    color: '#213D61',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cell: {
    borderWidth: 1,
    borderColor: '#000000', // Black outline for each cell
  },
  promptButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 5,
  },
  promptButtonText: {
    color: '#213D61',
    fontWeight: 'bold',
  },
  promptText: {
    marginTop: 10,
    fontSize: 16,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'semibold',
  },
  saveButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 5,
  },
  saveButtonText: {
    color: '#213D61',
    fontWeight: 'bold',
  },
  clearButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: 'red', // Change color to red for visibility
    borderRadius: 5,
  },
  clearButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});

export default PaintByNumbers;
